spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: file-storing-service
          uri: http://file-storing-service:8080
          predicates:
            - Path=/files/**
        - id: file-analysis-service
          uri: http://file-analysis-service:8080
          predicates:
            - Path=/analysis/**
      globalcors:
        corsConfigurations:
          '[/**]':              # ← все пути
            allowedOrigins:     # домены фронта
              - "http://localhost:5173"
              - "https://front.prod.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true