spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: file-storing-service
          uri: http://file-storing-service:8081
          predicates:
            - Path=/files/**
        - id: file-analysis-service
          uri: http://file-analysis-service:8082
          predicates:
            - Path=/analysis/**
